name: brain-diffuser
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alabaster=0.7.12=pyhd3eb1b0_0
  - arrow=1.2.2=pyhd3eb1b0_0
  - astroid=2.11.7=py38h06a4308_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=22.6.0=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - chardet=4.0.0=py38h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.5=py38h06a4308_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=38.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - docutils=0.18.1=py38h06a4308_3
  - entrypoints=0.4=py38h06a4308_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - flake8=4.0.1=pyhd3eb1b0_1
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - imagesize=1.4.1=py38h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - inflection=0.5.1=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py38h06a4308_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=0.9.0=py38h7f8727e_0
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.4.0=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - keyring=23.4.0=py38h06a4308_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.6.0=py38h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mypy_extensions=0.4.3=py38h06a4308_1
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.3.0=py38h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.23.4=py38h14f4228_0
  - numpy-base=1.23.4=py38h31eccc5_0
  - numpydoc=1.4.0=py38h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.5.1=py38h417a72b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.9.0=py38h06a4308_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hace64e9_1
  - pluggy=1.0.0=py38h06a4308_1
  - ply=3.11=py38_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.14.5=py38h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pyqtwebengine=5.15.7=py38h6a678d5_1
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-lsp-black=1.2.1=py38h06a4308_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.5.0=py38h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py38h06a4308_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.2=py38h06a4308_0
  - qtpy=2.2.0=py38h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py38h06a4308_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py38h06a4308_1
  - scikit-learn=1.1.3=py38h6a678d5_0
  - secretstorage=3.3.1=py38h06a4308_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=5.0.2=py38h06a4308_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.3.3=py38h06a4308_0
  - spyder-kernels=2.3.3=py38h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - testpath=0.6.0=py38h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38h06a4308_0
  - tomlkit=0.11.1=py38h06a4308_0
  - torchvision=0.13.1=py38_cu113
  - typing-extensions=4.3.0=py38h06a4308_0
  - typing_extensions=4.3.0=py38h06a4308_0
  - ujson=5.4.0=py38h6a678d5_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.12=py38h06a4308_0
  - watchdog=2.1.6=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - whatthepatch=1.0.2=py38h06a4308_0
  - wrapt=1.14.1=py38h5eee18b_0
  - wurlitzer=3.0.2=py38h06a4308_0
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.3.0
      - antlr4-python3-runtime==4.8
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - clip==1.0
      - cycler==0.11.0
      - easydict==1.9
      - einops==0.3.0
      - filelock==3.8.0
      - fire==0.4.0
      - ftfy==6.1.1
      - gauss==0.0.9
      - grpcio==1.50.0
      - h5py==3.7.0
      - huggingface-hub==0.11.0
      - imageio==2.22.4
      - importlib-metadata==5.0.0
      - ipykernel==5.3.4
      - ipython==7.22.0
      - ipywidgets==8.0.4
      - jupyter==1.0.0
      - jupyter-client==7.4.8
      - jupyter-console==6.4.4
      - jupyter-core==5.1.1
      - jupyter-events==0.5.0
      - jupyter-server==2.0.6
      - jupyter-server-terminals==0.4.3
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - kornia==0.6.8
      - lpips==0.1.3
      - markdown==3.4.1
      - matplotlib==3.4.2
      - nbclassic==0.4.8
      - networkx==2.8.8
      - nibabel==4.0.2
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - omegaconf==2.1.1
      - opencv-python==4.5.1.48
      - pdf2image==1.16.0
      - pip==22.3.1
      - platformdirs==2.6.2
      - prometheus-client==0.15.0
      - protobuf==4.21.9
      - pydeprecate==0.3.2
      - pymupdf==1.21.1
      - pyparsing==3.0.9
      - python-json-logger==2.0.4
      - pywavelets==1.4.1
      - pyyaml==5.4.1
      - pyzmq==24.0.1
      - regex==2022.10.31
      - scikit-image==0.17.2
      - scipy==1.9.3
      - send2trash==1.8.0
      - setuptools==65.6.0
      - sniffio==1.3.0
      - ssim-pil==1.0.14
      - tensorboard==1.15.0
      - tensorboardx==2.1
      - termcolor==2.1.1
      - terminado==0.17.1
      - tifffile==2022.10.10
      - tokenizers==0.12.1
      - torchmetrics==0.7.3
      - tornado==6.2
      - tqdm==4.60.0
      - traitlets==5.8.0
      - transformers==4.19.2
      - websocket-client==1.4.2
      - werkzeug==2.2.2
      - wheel==0.38.4
      - widgetsnbextension==4.0.5
      - zipp==3.10.0
